/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pacote_banco_dados.ClasseConexao;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author cliente
 */
public class ListarVendas extends javax.swing.JInternalFrame {
    
    Connection conexao = null;
    PreparedStatement comando = null;
    ResultSet resultado = null;

    /**
     * Creates new form ListarVendas
     */
    public ListarVendas() {
        initComponents();
        conexao = ClasseConexao.Conectar();
    }
    
    private void pesquisarVendas() {
       String sql = "select cod_compra,data_compra,cod_cliente,cod_prod,forma_pagamento,valor_pagamento,parcelas,situacao from pagamentos where cod_compra like ?";
        try {
            comando = conexao.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            comando.setString(1, txtPesquisaVenda.getText() + "%");
            resultado = comando.executeQuery();

            tabVendas.setModel(DbUtils.resultSetToTableModel(resultado));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisaVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVendas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lista de Vendas");

        txtPesquisaVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaVendaKeyReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa.png"))); // NOI18N

        tabVendas = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tabVendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabVendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tabVendas.setForeground(new java.awt.Color(51, 51, 51));
        tabVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "cod_compra", "data_compra", "cod_cliente", "cod_prod", "forma_pagamento", "valor_pagamento", "parcelas", "situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabVendas.setFocusable(false);
        tabVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabVendas);
        if (tabVendas.getColumnModel().getColumnCount() > 0) {
            tabVendas.getColumnModel().getColumn(0).setResizable(false);
            tabVendas.getColumnModel().getColumn(1).setResizable(false);
            tabVendas.getColumnModel().getColumn(2).setResizable(false);
            tabVendas.getColumnModel().getColumn(3).setResizable(false);
            tabVendas.getColumnModel().getColumn(4).setResizable(false);
            tabVendas.getColumnModel().getColumn(5).setResizable(false);
            tabVendas.getColumnModel().getColumn(6).setResizable(false);
            tabVendas.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaVendaKeyReleased
        // TODO add your handling code here:
        pesquisarVendas();
    }//GEN-LAST:event_txtPesquisaVendaKeyReleased

    private void tabVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVendasMouseClicked
        // TODO add your handling code here:
        //int confirma = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA REMOVER ESTE PRODUTO?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_tabVendasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabVendas;
    private javax.swing.JTextField txtPesquisaVenda;
    // End of variables declaration//GEN-END:variables
}
