/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.beans.PropertyVetoException;
import java.sql.*;
import pacote_banco_dados.ClasseConexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;


/**
 *
 * @author cliente
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement comando = null;
    ResultSet resultado = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ClasseConexao.Conectar();
        System.out.println(conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        Telinha = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        mnCliente = new javax.swing.JMenu();
        gerenciarCli = new javax.swing.JMenuItem();
        mnProduto = new javax.swing.JMenu();
        gerenciarProd = new javax.swing.JMenuItem();
        mnPagamento = new javax.swing.JMenu();
        contaReceber = new javax.swing.JMenuItem();
        listarVendas = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        sobre = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOFTSHOES");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(Telinha);
        Telinha.setBounds(0, 0, 900, 425);

        Menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Menu.setPreferredSize(new java.awt.Dimension(267, 35));

        mnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_2124114_add_user_icon_24px.png"))); // NOI18N
        mnCliente.setText("CLIENTES     ");
        mnCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        gerenciarCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        gerenciarCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gerenciarCli.setText("GERENCIAR CLIENTE");
        gerenciarCli.setToolTipText("GERENCIAR CLIENTE");
        gerenciarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarCliActionPerformed(evt);
            }
        });
        mnCliente.add(gerenciarCli);

        Menu.add(mnCliente);

        mnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tenis.png"))); // NOI18N
        mnProduto.setText("PRODUTOS     ");
        mnProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        gerenciarProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        gerenciarProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gerenciarProd.setText("GERENCIAR PRODUTO");
        gerenciarProd.setToolTipText("GERENCIAR PRODUTO");
        gerenciarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarProdActionPerformed(evt);
            }
        });
        mnProduto.add(gerenciarProd);

        Menu.add(mnProduto);

        mnPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/payy.png"))); // NOI18N
        mnPagamento.setText("VENDAS     ");
        mnPagamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        contaReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        contaReceber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contaReceber.setText("GERENCIAR VENDAS");
        contaReceber.setToolTipText("GERENCIAR VENDAS");
        contaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaReceberActionPerformed(evt);
            }
        });
        mnPagamento.add(contaReceber);

        listarVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        listarVendas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listarVendas.setText("LISTAR VENDAS");
        listarVendas.setToolTipText("LISTAR VENDAS");
        listarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarVendasActionPerformed(evt);
            }
        });
        mnPagamento.add(listarVendas);

        Menu.add(mnPagamento);

        mnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sobre.png"))); // NOI18N
        mnAjuda.setText("AJUDA     ");
        mnAjuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        sobre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sobre.setText("SOBRE");
        sobre.setToolTipText("SOBRE");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        mnAjuda.add(sobre);

        Menu.add(mnAjuda);

        mnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/exit.png"))); // NOI18N
        mnSair.setText("OPÇÕES     ");
        mnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sair.setText("SAIR");
        Sair.setToolTipText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        mnSair.add(Sair);

        Menu.add(mnSair);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(916, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarCliActionPerformed
        // TODO add your handling code here:
        GerenciarCliente gerenciarCli = new GerenciarCliente();
        
        gerenciarCli.setVisible(true);
        Telinha.add(gerenciarCli);
        
    }//GEN-LAST:event_gerenciarCliActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
        
    }//GEN-LAST:event_sobreActionPerformed

    private void contaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaReceberActionPerformed
        // TODO add your handling code here:
        ContasReceber contaReceber = new ContasReceber();
        
        contaReceber.setVisible(true);
        Telinha.add(contaReceber);
    }//GEN-LAST:event_contaReceberActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
                // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        int saira = JOptionPane.showConfirmDialog(null, "TEM CERTEZA QUE DESEJA SAIR?","ATENÇÃO",JOptionPane.YES_NO_OPTION);
        if (saira == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_SairActionPerformed

    private void gerenciarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarProdActionPerformed
        // TODO add your handling code here:
        GerenciarProduto gerenciarProd = new GerenciarProduto();
        
        gerenciarProd.setVisible(true);
        Telinha.add(gerenciarProd);
    }//GEN-LAST:event_gerenciarProdActionPerformed

    private void listarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarVendasActionPerformed
        // TODO add your handling code here:
        ListarVendas listarVendas = new ListarVendas();
        listarVendas.setVisible(true);
        Telinha.add(listarVendas);
    }//GEN-LAST:event_listarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JDesktopPane Telinha;
    private javax.swing.JMenuItem contaReceber;
    private javax.swing.JMenuItem gerenciarCli;
    private javax.swing.JMenuItem gerenciarProd;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listarVendas;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenu mnPagamento;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration//GEN-END:variables
}
